version: 0.1.0

services:
  app:
    build:
      context: ./App
      dockerfile: Dockerfile
    ports: 
      - 1337:80
  server: 
    build: 
      context: ./Server
      dockerfile: Dockerfile
    ports: 
      - 1227:80
