version: 0.2.0

services:
  app:
    image: luviz/dockertest/app
    container_name: luviz-dockertest-app
    build:
      context: ./App
      dockerfile: Dockerfile
    environment: 
      - server=http://srv.local
      - server_port=80
    ports: 
      - 1337:80
    hostname: app.local
  server: 
    image: luviz/dockertest/server
    container_name: luviz-dockertest-server
    build: 
      context: ./Server
      dockerfile: Dockerfile
    ports: 
      - 1227:80
    hostname: srv.local
